title: Collections Model Documentation
description: All the document related to the CHIN's Collection Model Documentation
theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - introduction.md
